"""The allowlist, deny-list, and agent-contact set keep sensitive fields out.

Also checks `check_column` error paths, allowlisted names against the generated
schema notes (when present), and the flag/city helpers in `valid_values`.
"""

import pathlib
import re

import pytest

from idx_agent.domain import valid_values
from idx_agent.safety import columns

# Generated by the WO-002 profiling run; the test that reads it skips until it exists.
NOTES = (
    pathlib.Path(__file__).resolve().parents[1] / "docs" / "data" / "schema_notes.md"
)


def test_allowlist_and_denylist_are_disjoint():
    """No column is both allowed and deny-listed."""
    assert not columns.ALL_ALLOWED & columns.DENYLIST


def test_no_agent_contact_field_is_allowlisted():
    """No agent-contact name is allowed, by set or by name pattern."""
    assert not columns.ALL_ALLOWED & columns.AGENT_CONTACT
    for name in columns.ALL_ALLOWED:
        assert not re.search(r"Agent.*(Email|Phone|Name)|^LA[0-9]_", name), name


def test_denylist_covers_every_candidate_from_the_safety_invariants():
    """Every deny-list candidate named in SAFETY_INVARIANTS.md is in DENYLIST."""
    candidates = {
        "AccessCode",
        "LockBoxSerialNumber",
        "LockBoxLocation",
        "PrivateRemarks",
        "PrivateOfficeRemarks",
        "ShowingInstructions",
        "OwnerName",
        "OwnerPhone",
        "OccupantName",
        "OccupantPhone",
    }
    assert candidates <= columns.DENYLIST


def test_check_column_enforces_the_lists():
    """One allowed column passes; each of the four rejection reasons raises."""
    assert columns.check_column("california_sold", "ClosePrice") == "ClosePrice"
    with pytest.raises(ValueError, match="deny-listed"):
        columns.check_column("rets_property", "PrivateRemarks")
    with pytest.raises(ValueError, match="agent contact"):
        columns.check_column("rets_property", "ListAgentEmail")
    with pytest.raises(ValueError, match="not allowlisted"):
        columns.check_column("rets_property", "SomeOtherColumn")
    with pytest.raises(ValueError, match="unknown table"):
        columns.check_column("users", "id")


@pytest.mark.skipif(
    not NOTES.exists(),
    reason="docs/data/schema_notes.md arrives with the profiling run",
)
def test_every_allowlisted_column_exists_in_the_schema_notes():
    """Each allowed name appears in schema_notes.md as a table cell or code span."""
    text = NOTES.read_text(encoding="utf-8")
    missing = sorted(
        c
        for c in columns.ALL_ALLOWED
        if f"| {c} |" not in text and f"`{c}`" not in text
    )
    assert not missing, f"allowlisted but not in schema_notes.md: {missing}"


def test_flags_and_city_normalization():
    """Flag parsing follows the data's encoding; city names normalize case/spacing."""
    assert valid_values.parse_flag("1") is True
    assert valid_values.parse_flag("Y") is True
    assert valid_values.parse_flag("no") is False
    assert valid_values.parse_flag("") is False  # not marked
    assert valid_values.parse_flag(None) is None  # unknown
    assert valid_values.parse_flag("maybe") is None
    assert valid_values.normalize_city("  san  JOSE ") == "San Jose"


def test_value_sets_come_from_the_profiling_run():
    """The sets are filled: cities loaded, subtypes and the active rule fixed."""
    assert valid_values.PROVISIONAL is False
    assert len(valid_values.CITIES) > 1000
    assert "Los Angeles" in valid_values.CITIES
    assert {
        "SingleFamilyResidence",
        "Condominium",
        "Townhouse",
    } <= valid_values.SUBTYPES
    assert valid_values.ACTIVE_STATUS_COLUMN == "StandardStatus"
    assert valid_values.ACTIVE_STATUS_VALUES == {"Active"}
